version: '3.8'

services:
  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: trader-go-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password1
      MYSQL_DATABASE: trader_go
      MYSQL_USER: tradergo
      MYSQL_PASSWORD: password1
    networks:
      - trader-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trader-go-app
    ports:
      - "10000:10000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=trader_go
      - DB_USER=tradergo
      - DB_PASSWORD=password1
    volumes:
      - ./resources:/app/resources
    networks:
      - trader-network

networks:
  trader-network:
    driver: bridge
